apiVersion: azure.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: aks-app-cluster-02
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: ../testhooks/azure-release-delete.sh
spec:
  parameters:
    id: aks-app-cluster-02
    region: East US
    version: "1.29.2"
    nodes:
      count: 3
      instanceType: Standard_B2s
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
    deletionPolicy: Delete
    providerConfigName: default
  writeConnectionSecretToRef:
    name: aks-app-cluster-02-kubeconfig
