apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: aws-spoke-01
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: ../testhooks/aws-release-delete.sh
spec:
  parameters:
    id: aws-spoke-01
    region: us-west-1
    version: '1.27'
    iam:
      roleArn: >-
        arn:aws:iam::609897127049:role/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
    nodes:
      count: 3
      instanceType: t3.small
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
    deletionPolicy: Delete
    providerConfigName: default
  writeConnectionSecretToRef:
    name: aws-spoke-01-kubeconfig
