apiVersion: dbaas.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: marketing-services-aws-mariadb
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: aws
  parameters:
    region: us-west-2
    engine: mariadb
    engineVersion: "10.11"
    storageGB: 5
    passwordSecretRef:
      namespace: default
      name: mariadbsecretaws
      key: password
  writeConnectionSecretToRef:
    name: marketing-services-aws-mariadb
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: mariadbsecretaws
  namespace: default
type: Opaque