apiVersion: dbaas.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  name: marketing-services-azure-mariadb
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      provider: azure
  parameters:
    region: westus
    engine: mariadb
    engineVersion: "10.3"
    storageGB: 5
    passwordSecretRef:
      namespace: default
      name: mariadbsecretazure
      key: password
  writeConnectionSecretToRef:
    name: marketing-services-azure-mariadb
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: mariadbsecretazure
  namespace: default
type: Opaque