apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ctp-dbaas-claims
  namespace: argocd
  labels:
    acmeco/team: dbaas
spec:
  project: default
  source:
    repoURL: https://github.com/upbound-demo/spaces-demo.git
    targetRevision: HEAD
    path: claims/dbaas
    directory:
      recurse: true
  destination:
    name: ctp-dbaas
    namespace: default