apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.gcp.caas.upbound.io
spec:
  group: gcp.caas.upbound.io
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  connectionSecretKeys:
  - kubeconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: Cluster configuration parameters.
                properties:
                  id:
                    type: string
                    description: ID of this Cluster that other objects will use to refer to it.
                    minLength: 1
                    maxLength: 34
                  region:
                    type: string
                    description: Region is the region you'd like your resource to be created in.
                  networkSelector:
                    type: string
                    description: NetworkSelector employs a specific type of network architecture.
                    enum:
                    - basic
                    default: basic
                  serviceSelector:
                    type: string
                    description: ServiceSelector employs a specific type of service architecture.
                    enum:
                    - default
                    - gitops-master
                    default: default
                  deletionPolicy:
                    description: When the Composition is deleted, delete the GCP resources. Defaults to Delete
                    enum:
                    - Delete
                    - Orphan
                    type: string
                    default: Delete
                  providerConfigName:
                    description: Crossplane ProviderConfig to use for provisioning this resources
                    type: string
                    default: default
                  version:
                    type: string
                    description: Kubernetes version of the Cluster
                    default: "latest"
                  nodes:
                    type: object
                    description: Cluster node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      instanceType:
                        type: string
                        description: instance types associated with the Node Group.
                        default: n1-standard-4
                    required:
                    - count
                    - instanceType
                  gitops:
                    type: object
                    description: GitOps configure external gitops system for mcp controlplane
                    properties:
                      url:
                        type: string
                        description: Url for GitOps Sync.
                      path:
                        type: string
                        description: path in Repo for GitOps Sync.
                      kubeConfigSecretRef:
                        type: object
                        description: location for kubeconfig mcp controlplane
                        properties:
                          name:
                            type: string
                            description: Name of the secret.
                          namespace:
                            type: string
                            description: Namespace of the secret.
                        required:
                        - name
                        - namespace
                    required:
                    - url
                  services:
                    type: object
                    description: Services configuration parameters.
                    properties:
                      operators:
                        type: object
                        description: Configuration for operators.
                        properties:
                          flux:
                            type: object
                            description: Configuration for the Flux GitOps operator.
                            properties:
                              version:
                                type: string
                                description: Flux operator version to run.
                                default: "2.9.2"
                required:
                - nodes
                - id
                - region
                - deletionPolicy
                - providerConfigName
            required:
            - parameters
