apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xgke.gcp.caas.upbound.io
spec:
  connectionSecretKeys:
  - kubeconfig
  group: gcp.caas.upbound.io
  names:
    kind: XGKE
    plural: xgke
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: GKE configuration parameters.
                properties:
                  id:
                    type: string
                    description: ID of this Cluster that other objects will use to refer to it.
                    minLength: 1
                    maxLength: 34
                  region:
                    type: string
                    description: Region is the region you'd like your resource to be created in.
                  deletionPolicy:
                    description: When the Composition is deleted, delete the GCP resources. Defaults to Delete
                    enum:
                    - Delete
                    - Orphan
                    type: string
                    default: Delete
                  providerConfigName:
                    description: Crossplane ProviderConfig to use for provisioning this resources
                    type: string
                    default: default
                  version:
                    description: Kubernetes version 
                    type: string
                    default: "latest"
                  nodes:
                    type: object
                    description: GKE node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count, from 1 to 100.
                      instanceType:
                        type: string
                        description: instance types associated with the Node Group.
                        default: n1-standard-4
                    required:
                    - count
                    - instanceType
                required:
                - id
                - region
                - deletionPolicy
                - providerConfigName
                - nodes
            required:
            - parameters
          status:
            description: A Status represents the observed state
            properties:
              gke:
                description: Freeform field containing status information for gke
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
