apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  projectID: "558115617928"
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: gcp-secret
      key: creds