apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.12.1