apiVersion: gcp.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: consumer-services-gke-01
  namespace: default
  annotations:
    uptest.upbound.io/pre-delete-hook: ../testhooks/gcp-release-delete.sh
spec:
  parameters:
    id: consumer-services-gke-01
    region: us-west2
    version: "latest"
    nodes:
      count: 3
      instanceType: n1-standard-4
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
    deletionPolicy: Delete
    providerConfigName: default
  writeConnectionSecretToRef:
    name: consumer-services-gke-01-kubeconfig
