apiVersion: azure.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: marketing-services-aks-cluster-01
  namespace: marketing-services
  annotations:
    uptest.upbound.io/pre-delete-hook: ../testhooks/azure-release-delete.sh
spec:
  parameters:
    id: marketing-services-aks-cluster-01
    region: East US
    version: "1.28.5"
    nodes:
      count: 3
      instanceType: Standard_B2s
    gitops:
      url: https://github.com/upbound/caas-cluster-configuration
    deletionPolicy: Delete
    providerConfigName: marketing-services
  writeConnectionSecretToRef:
    name: marketing-services-aks-cluster-01-kubeconfig
